bindx.o: bindx.c bindx_c.h bindx_parse.h bindx_util.h \
 prototypes/bindx_util_p.h prototypes/bindx_parse_p.h bindx_parse_int.h \
 prototypes/bindx_parse_int_p.h prototypes/bindx_c_p.h bindx_cpp.h \
 prototypes/bindx_cpp_p.h bindx_f90.h prototypes/bindx_f90_p.h \
 bindx_f77.h prototypes/bindx_f77_p.h bindx_idl.h \
 prototypes/bindx_idl_p.h bindx_py.h prototypes/bindx_py_p.h \
 bindx_yylex_int.h
bindx_c.o: bindx_c.c bindx_c.h bindx_parse.h bindx_util.h \
 prototypes/bindx_util_p.h prototypes/bindx_parse_p.h bindx_parse_int.h \
 prototypes/bindx_parse_int_p.h prototypes/bindx_c_p.h
bindx_cpp.o: bindx_cpp.c bindx_c.h bindx_parse.h bindx_util.h \
 prototypes/bindx_util_p.h prototypes/bindx_parse_p.h bindx_parse_int.h \
 prototypes/bindx_parse_int_p.h prototypes/bindx_c_p.h bindx_cpp.h \
 prototypes/bindx_cpp_p.h
bindx_f77.o: bindx_f77.c bindx_c.h bindx_parse.h bindx_util.h \
 prototypes/bindx_util_p.h prototypes/bindx_parse_p.h bindx_parse_int.h \
 prototypes/bindx_parse_int_p.h prototypes/bindx_c_p.h bindx_f77.h \
 prototypes/bindx_f77_p.h
bindx_f90.o: bindx_f90.c bindx_c.h bindx_parse.h bindx_util.h \
 prototypes/bindx_util_p.h prototypes/bindx_parse_p.h bindx_parse_int.h \
 prototypes/bindx_parse_int_p.h prototypes/bindx_c_p.h bindx_f90.h \
 prototypes/bindx_f90_p.h
bindx_idl.o: bindx_idl.c bindx_c.h bindx_parse.h bindx_util.h \
 prototypes/bindx_util_p.h prototypes/bindx_parse_p.h bindx_parse_int.h \
 prototypes/bindx_parse_int_p.h prototypes/bindx_c_p.h bindx_idl.h \
 prototypes/bindx_idl_p.h
bindx_parse.o: bindx_parse.c bindx_parse.h bindx_util.h \
 prototypes/bindx_util_p.h prototypes/bindx_parse_p.h
bindx_parse_int.o: bindx_parse_int.c bindx_parse.h bindx_util.h \
 prototypes/bindx_util_p.h prototypes/bindx_parse_p.h bindx_parse_int.h \
 prototypes/bindx_parse_int_p.h bindx_yylex_int.h
bindx_py.o: bindx_py.c bindx_c.h bindx_parse.h bindx_util.h \
 prototypes/bindx_util_p.h prototypes/bindx_parse_p.h bindx_parse_int.h \
 prototypes/bindx_parse_int_p.h prototypes/bindx_c_p.h bindx_py.h \
 prototypes/bindx_py_p.h
bindx_util.o: bindx_util.c bindx_parse.h bindx_util.h \
 prototypes/bindx_util_p.h prototypes/bindx_parse_p.h
bindx_yylex_int.o: bindx_yylex_int.c bindx_parse.h bindx_util.h \
 prototypes/bindx_util_p.h prototypes/bindx_parse_p.h bindx_parse_int.h \
 prototypes/bindx_parse_int_p.h
gindex_name_value.o: gindex_name_value.c gutil.h gindex_name_value.h
glist.o: glist.c gutil.h glist.h
gutil_error.o: gutil_error.c gutil.h
gutil_string.o: gutil_string.c gutil.h
