/* bindx_yylex_int.c */
int yy_lex(locus_data *locus, lex_type_data *lex_type);
void yy_restart(FILE *input_file);
void yy__switch_to_buffer(YY_BUFFER_STATE new_buffer);
YY_BUFFER_STATE yy__create_buffer(FILE *file, int size);
void yy__delete_buffer(YY_BUFFER_STATE b);
void yy__flush_buffer(YY_BUFFER_STATE b);
void yy_push_buffer_state(YY_BUFFER_STATE new_buffer);
void yy_pop_buffer_state(void);
YY_BUFFER_STATE yy__scan_buffer(char *base, yy_size_t size);
YY_BUFFER_STATE yy__scan_string(const char *yystr);
YY_BUFFER_STATE yy__scan_bytes(const char *yybytes, int _yybytes_len);
int yy_get_lineno(void);
FILE *yy_get_in(void);
FILE *yy_get_out(void);
int yy_get_leng(void);
char *yy_get_text(void);
void yy_set_lineno(int line_number);
void yy_set_in(FILE *in_str);
void yy_set_out(FILE *out_str);
int yy_get_debug(void);
void yy_set_debug(int bdebug);
int yy_lex_destroy(void);
void *yy_alloc(yy_size_t size);
void *yy_realloc(void *ptr, yy_size_t size);
void yy_free(void *ptr);
char *get_yytext(void);
void comment(locus_data *locus);
void yypreinclude(FILE *fp);
void yypostinclude(void);
void yyrewind(int r, lex_type_data *type);
