/* bindx_yylex_test.c */
int yy_test_lex(locus_data *locus, lex_type_data *lex_type);
void yy_test_restart(FILE *input_file);
void yy_test__switch_to_buffer(YY_BUFFER_STATE new_buffer);
YY_BUFFER_STATE yy_test__create_buffer(FILE *file, int size);
void yy_test__delete_buffer(YY_BUFFER_STATE b);
void yy_test__flush_buffer(YY_BUFFER_STATE b);
void yy_test_push_buffer_state(YY_BUFFER_STATE new_buffer);
void yy_test_pop_buffer_state(void);
YY_BUFFER_STATE yy_test__scan_buffer(char *base, yy_size_t size);
YY_BUFFER_STATE yy_test__scan_string(const char *yystr);
YY_BUFFER_STATE yy_test__scan_bytes(const char *yybytes, int _yybytes_len);
int yy_test_get_lineno(void);
FILE *yy_test_get_in(void);
FILE *yy_test_get_out(void);
int yy_test_get_leng(void);
char *yy_test_get_text(void);
void yy_test_set_lineno(int line_number);
void yy_test_set_in(FILE *in_str);
void yy_test_set_out(FILE *out_str);
int yy_test_get_debug(void);
void yy_test_set_debug(int bdebug);
int yy_test_lex_destroy(void);
void *yy_test_alloc(yy_size_t size);
void *yy_test_realloc(void *ptr, yy_size_t size);
void yy_test_free(void *ptr);
char *get_yytext_test(void);
void comment_test(locus_data *locus);
void yypreinclude_test(FILE *fp);
void yypostinclude_test(void);
void yyrewind_test(int r, lex_type_data *type);
